---
- name: load var files
  include_vars: "{{ item }}"
  with_items:
   - stack-user.yml
   - repo.yml
   - local-conf.yml

- name: create stack user
  include: add-stack-user.yml

- name: let stack user be without password requirement
  shell: echo "'{{ stack_user }} ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers"

- name: clone devstack
  include: clone-devstack.yml

- name: copy local.conf
  include: copy-local-conf.yml

- name: install openstack
  include: install-openstack.yml
