---
- name: load var files
  include_vars: "{{ item }}"
  with_items:
   - stack-user.yml
   - repo.yml
   - local-conf.yml

- name: create stack user
  include: add-stack-user.yml

- name: stack user without password
  script: "{{ stack_without_password_src }}.sh"

- name: clone devstack
  include: clone-devstack.yml

- name: copy local.conf
  include: copy-local-conf.yml

- name: install openstack
  include: install-openstack.yml
