---
- name: load var files
  include_vars: "{{ item }}"
  with_items:
   - "{{ stack_user_file }}.yml"
   - "{{ repo_file }}.yml" 

- name: stack user configurations
  include: add-stack-user.yml

- name: clone devstack
  include: clone-devstack.yml
